name: Python CI
on:
  push:
    branches: [master, main, ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [3.9, 3.10]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Python ${{ matrix.node-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.node-version }}
      - name: Checkout node
        uses: actions/checkout@v2
      - name: Test
        run: python py/test_money.py -v
        shell: bash
